input {
  file {
    path => "/data/movies_dataset.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    tags => ["raw"]
  }
}

filter {
  if "raw" in [tags] {
    csv {
      separator => ","
      skip_header => true
      columns => ["index", "title", "original_language", "release_date", "popularity", "vote_average", "vote_count", "overview"]
    }

    if [index] == "index" or [index] == "" {
      drop { }
    }

    mutate {
      add_field => { "ingested_at" => "%{@timestamp}" }
      remove_field => ["message", "host", "@version", "event", "log", "file"]
    }
  }
}

output {
  if "raw" in [tags] {
    elasticsearch {
      hosts => ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"] # Sécurité: variable d'environnement
      index => "movies_raw"
      document_id => "%{index}"
    }
  }
}
